version: '3.5'
services:
    mongo:
        container_name: mongo
        image: mongo:4.2
        networks:
            - bubble
        ports:
            - 27018:27017
        command: mongod --maxConns 10000
networks:
    bubble:
        driver: bridge
        external: true